---
title: "Überarbeitung Erstes Netzwerk"
author: "Alice Kärcher"
date: "2023-11-15"
output: html_document
---

# Setup des Dokuments

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
```

## Codebuch und Datensatz via Github

```{r Netzwerk einlesen}

# Einlesen der Edgelist aus github link: beachte den Separator ","
modernfamily_edgelist <- read.csv("https://raw.githubusercontent.com/ak349hdm/SNA-2.3-eigenes-Netzwerk/main/modernfamily_edgelist.csv", header=T, as.is=T, sep = ";")

# Einlesen der Nodelist
modernfamily_Nodelist <- read.csv("https://raw.githubusercontent.com/ak349hdm/SNA-2.3-eigenes-Netzwerk/main/modernfamily_Nodelist.csv", header=T, as.is=T, sep = ";")

# Überprüfen der Daten (nur, falls notwendig)
 head(modernfamily_edgelist)
 head(modernfamily_Nodelist)

# wandelt die Edgelist als Matrix um.
edgematrix <-as.matrix(modernfamily_edgelist)


# erstellt ein igraph-objekt aus der Fusion von Edge- und Nodelist
modernfamily <- graph_from_data_frame(d=edgematrix, vertices= modernfamily_Nodelist, directed=T)

# das igraph-Objekt heisst jetzt modernfamily und ist ein gerichtetes Netzwerk.
modernfamily

```


# Visualisierung

```{r Einfache Visualisierung, fig.height=3, fig.width=4}
plot(modernfamily,
     edge.arrow.size=.3,
     layout=layout_with_kk,
     main="Modern Family Netzwerk",
     sub="Interlocking Relationships, n=2 Fälle")

```






